export const MAX_NAME_LENGTH = 100
export const MAX_SUBJECT_LENGTH = 150
export const MAX_MESSAGE_LENGTH = 2000
export const MESSAGE_RATE_LIMIT_MAX_REQUESTS_PER_15_MINS = 2
export const MAILING_LIST_RATE_LIMIT_MAX_REQUESTS_PER_15_MINS = 3
